#
# This multi container compose is a demo and proof of concept of openmpi over ssh between containers.
#  not an attempt to show performance gains or scalability for WRF execution
#
# in this pwd/
#  docker-compose up 
#   when seeing, "wrfleader exited with code 0"  press Ctrl-C
#  docker-compose stop
#  docker-compose rm
#
wrfvol: 
  image: bigwxwrf/ncar-wrf
  command:
   - /bin/true
#
wpsgeog: 
  image: bigwxwrf/ncar-wpsgeog
wrfinput: 
  image: bigwxwrf/ncar-wrfinputsandy
#
wrfsandy-leader: 
  command: 
    - /wrf/run-wrf
    - "-np"
    - "4"
    - "-slots"
    - "2"
    - "-iface"
    - "eth0"
    - "-hosts"
    - "wrfslave-1,wrfslave-2"
  container_name: wrfleader
  links: 
    - wrfsandy-slave-1
    - wrfsandy-slave-2
  image: bigwxwrf/ncar-wrf
  volumes: 
    - "~/wrfoutput:/wrfoutput"
  volumes_from: 
    - wpsgeog
    - wrfinput
    - wrfvol
#
wrfsandy-slave-1: 
  command: 
    - /usr/sbin/sshd
    - "-D"
  container_name: wrfslave-1
  image: bigwxwrf/ncar-wrf
  volumes: 
    - "~/wrfoutput:/wrfoutput"
  volumes_from: 
    - wpsgeog
    - wrfinput
    - wrfvol
#
wrfsandy-slave-2: 
  command: 
    - /usr/sbin/sshd
    - "-D"
  container_name: wrfslave-2
  image: bigwxwrf/ncar-wrf
  volumes: 
    - "~/wrfoutput:/wrfoutput"
  volumes_from: 
    - wpsgeog
    - wrfinput
    - wrfvol
